/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omfbreports;

import com.qoppa.pdfWriter.PDFPrinterJob;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import net.sf.image4j.codec.bmp.BMPDecoder;

/**
 *
 * @author Emmanuel Ikpe
 */
public class AGMInvite extends javax.swing.JFrame implements Printable{

    /**
     * Creates new form AGMInvite
     */
    public AGMInvite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelname = new javax.swing.JLabel();
        jLabeladdress = new javax.swing.JLabel();
        jLabeladdress2 = new javax.swing.JLabel();
        jLabelcount = new javax.swing.JLabel();
        jLabelpix = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ImageIcon icon= new ImageIcon(this.getClass().getResource("AGMLetter.jpg"));
        final Image img=icon.getImage();
        this.setIconImage(img);
        jPanel1 =new javax.swing.JPanel() {

            public void paintComponent(Graphics g){
                g.drawImage( img,0,0,getWidth(),getHeight(),this);
            }
        };

        jLabelname.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabelname.setText("jLabel1");
        jLabelname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelnameMouseClicked(evt);
            }
        });

        jLabeladdress.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabeladdress.setText("jLabel1");

        jLabeladdress2.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabeladdress2.setText("jLabel1");

        jLabelcount.setText("jLabel1");
        jLabelcount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeladdress2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelname, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jLabelpix, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabelcount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelcount)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabelname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabeladdress)
                        .addGap(11, 11, 11)
                        .addComponent(jLabeladdress2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabelpix, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(680, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
Connection conn=glob.getConnect(); 
String pixpath="";
 String cusno="";
try{
    Statement stmt2= conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
Statement stmt= conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
 current= stmt.executeQuery("select  name,address,cust_no from customer where cust_no in ( select ac_no from memtrans " +
"where gl_no='300105' and ac_no >'000000' and  ses_date<='2018-12-31 00:00:00.000' " +
"group by ac_no  having ABS(SUM(amount))>0) order by cust_no") ;
 int count=1;

while (current.next()){
    jLabelcount.setText(count+"");
jLabelname.setText(current.getString("name").trim()+",");
String street=current.getString("address").replaceAll("LTD", "PLC");
String[] address=current.getString("address").split("\\s+");
 cusno=current.getString("cust_no");
int len=address.length;
String city="";

for(int i=0; i<len;i++){
if(address[i].equalsIgnoreCase("Road")||address[i].equalsIgnoreCase("Street")||address[i].equalsIgnoreCase("Section")
        ||address[i].equalsIgnoreCase("School")||address[i].equalsIgnoreCase("Compound")||address[i].equalsIgnoreCase("Quarter")
        ||address[i].equalsIgnoreCase("layout")||address[i].equalsIgnoreCase("Lane")||address[i].equalsIgnoreCase("RD")){
  for(int n=i+1;n<len;n++){
     city=city+" "+address[n]; 
  }  
}
street=street.replace(city, "");

//retrieving pix
ResultSet current2 = stmt2.executeQuery("select sphoto,ssign from fssign where sphoto<>'' and cust_no="+cusno);
               if(current2.next()){//begin of A if
               pixpath="C:\\FinSolutions\\Photos\\"+current2.getString("sphoto");
               //String pixpath="\\\\Omfbserver\\e\\FinSolutions\\Photos\\"+current2.getString("sphoto");
               File tempFile = new File(pixpath);
             if (tempFile.exists()) { 
              //check for file extension for photo
              if(pixpath.contains(".bmp")||pixpath.contains(".BMP")){
             
             BufferedImage image = BMPDecoder.read(new File(pixpath));//photo
                    ImageIcon icon = new ImageIcon(image.getScaledInstance(70,70, Image.SCALE_SMOOTH));//photo
                  jLabelpix.setIcon(icon);//photo
                       //JOptionPane.showMessageDialog(this,current.getString("sphoto")+" and "+pixpath);
              }
              else{
               ImageIcon imageIcon = new ImageIcon(new ImageIcon(pixpath).getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH));//photo
               jLabelpix.setIcon(imageIcon);//photo
                   }
               
             }// end of testing if the file exist
             else{
              jLabelpix.setIcon(null);   
             }
               }//end of A if
               else{
                   jLabelpix.setIcon(null);
               }
    }
jLabeladdress.setText(street.trim()+",");
jLabeladdress2.setText(city.trim()+".");

// create a PDF Printer Job
            //PDFDocument pdfDoc = new PDFDocument ();
    	 PDFPrinterJob printer = (PDFPrinterJob)PDFPrinterJob.getPrinterJob ();
    	 // set the printable object 
    	 printer.setPrintable (this);
    	 // set number of copies to 1 
    	 printer.setCopies (1);
    	 // print and save the document
    	 printer.print(cusno+".pdf");
    	 // output done message 
   count=count+1; 	
}
JOptionPane.showMessageDialog(this,"Done!");
}
catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage()+" "+pixpath+"-"+cusno);}



    
    }//GEN-LAST:event_formWindowOpened

    private void jLabelnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelnameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelnameMouseClicked

    private void jLabelcountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcountMouseClicked
    
    }//GEN-LAST:event_jLabelcountMouseClicked

    
    /**
     * n @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AGMInvite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AGMInvite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AGMInvite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AGMInvite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AGMInvite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeladdress;
    private javax.swing.JLabel jLabeladdress2;
    private javax.swing.JLabel jLabelcount;
    private javax.swing.JLabel jLabelname;
    private javax.swing.JLabel jLabelpix;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
Global glob= new Global();
ResultSet current;


public int print (Graphics g, PageFormat pf, int pageIndex) 
    {
    	if (pageIndex == 0)
    	{
 
          // translate the graphics for margins
    	  g.translate(2, 2);
 
    	 // JOptionPane.showMessageDialog(rootPane, jPanel1.getHeight());
    	  jPanel1.setBounds(new java.awt.Rectangle(0, 0, 620, 806));
    	   jPanel1.revalidate();
         jPanel1.repaint();
    	 // print the panel to the graphics on page 0
    	 jPanel1.print (g);
    	 return Printable.PAGE_EXISTS;
    	}
    	else
    	{
    	 return Printable.NO_SUCH_PAGE;
    	}
    }
}
