/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omfbreports;

import java.awt.Cursor;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel Ikpe
 */
public class Clientnameonly extends javax.swing.JFrame {

    /**
     * Creates new form Clientname
     */
    public Clientnameonly() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablename = new javax.swing.JTable();
        jButtonsearch = new javax.swing.JButton();
        jTextFieldAcc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablename2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAcc2 = new javax.swing.JTextField();
        jButtonsearch1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Client Name");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jScrollPane1ComponentShown(evt);
            }
        });

        jTablename.setBackground(new java.awt.Color(255, 153, 51));
        jTablename.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Branch", "Product", "GL A/C NO", "A/C NO", "Name", "Ref No/ Address", "ID Card", "Bank Verification No", "NUBAN Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablename.setShowHorizontalLines(isEnabled());
        jTablename.setShowVerticalLines(isEnabled());
        jTablename.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablenameMouseClicked(evt);
            }
        });
        jTablename.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablenameKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTablename);

        jButtonsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omfbreports/Resource/searchicon.PNG"))); // NOI18N
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });

        jTextFieldAcc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAccKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Search on A/C Name");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jScrollPane2ComponentShown(evt);
            }
        });

        jTablename2.setBackground(new java.awt.Color(255, 153, 51));
        jTablename2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "GL A/C NO", "A/C NO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablename2.setShowHorizontalLines(isEnabled());
        jTablename2.setShowVerticalLines(isEnabled());
        jTablename2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablename2MouseClicked(evt);
            }
        });
        jTablename2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTablename2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTablename2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Search on A/C NO");

        jTextFieldAcc2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAcc2KeyPressed(evt);
            }
        });

        jButtonsearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omfbreports/Resource/searchicon.PNG"))); // NOI18N
        jButtonsearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearch1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldAcc2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAcc2))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldAcc)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
String qq;
if(jTextFieldAcc.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "You must type \n something to search");
}else{
/////Clear previous search (if any)

    i=0;

        
    qq=query="select  branch,cust_no,name,id_card,address,phone,ref_no,Bank_VNO from customer where cust_no like '%"+jTextFieldAcc2.getText()+"%'"; 

//JOptionPane.showMessageDialog(rootPane, query);
        try{
            
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
               
                ResultSet current = stmt.executeQuery(qq);
                 this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                   jTablename.getColumnModel().getColumn(4).setPreferredWidth(100);
               jTablename.getColumnModel().getColumn(4).setPreferredWidth(400);
               jTablename.getColumnModel().getColumn(5).setPreferredWidth(500);
               
                 while(current.next()){
                     jTablename.getModel().setValueAt(current.getString("branch"), i, 0);
                    jTablename.getModel().setValueAt(current.getString("cust_no"), i, 3);
                    jTablename.getModel().setValueAt(current.getString("name").trim(), i, 4);
                    jTablename.getModel().setValueAt(current.getString("ref_no").trim()+"-"+current.getString("address").trim(), i, 5);

                    jTablename.getModel().setValueAt(current.getString("id_card"), i, 6);
                    jTablename.getModel().setValueAt(current.getString("Bank_VNO"), i, 7);

                     i=i+1;
                 }
                 
                 
                  this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));  
                 //JOptionPane.showMessageDialog(rootPane, i+" Records found ");
                   jTablename.requestFocusInWindow();
                  
                 current.close();                     

                 
}
catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(rootPane, e.getMessage());
}
  
 jTablename.requestFocusInWindow();

}               
    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void jTablenameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablenameMouseClicked
if(evt.getClickCount()==2 && !jTablename.getModel().getValueAt(jTablename.getSelectedRow(),3).toString().isEmpty())  {
  String sqlaccinfo="select m.cust_no cnum,name,ref_no,reg_date,phone,id_card,group_name,address,Bank_VNO,gl_no,ac_no,NUBAN_CODE,ac_status from member m inner join customer c on m.cust_no=c.cust_no" +
" where ac_no='"+jTablename.getModel().getValueAt(jTablename.getSelectedRow(),3)+"' and gl_no like'200%'";
          
            
  
                  try{
                      this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                ResultSet current = stmt.executeQuery(sqlaccinfo);
                 if(current.next()){
                 acctitle=current.getString("name");
                 regdate=current.getString("reg_date");
                 groupname=current.getString("group_name");
                 idcard=current.getString("ID_card");
                 cusno=current.getString("cnum");
                 BVN=current.getString("Bank_VNO");
                 accnoonly=current.getString("ac_no");
                accno=current.getString("gl_no")+"."+current.getString("ac_no");
                nuban=current.getString("nuban_code");
                ref=current.getString("ref_no");
                phone=current.getString("phone");
                addr=current.getString("address");
                status=current.getString("ac_status");
                if(status.equalsIgnoreCase("A")){status="Active";}
                else if(status.equalsIgnoreCase("C")){status="Closed";}
                else if(status.equalsIgnoreCase("D")){status="Dormant";}
                else if(status.equalsIgnoreCase("H")){status="On Hold";}
                 }
                while(i>0){
                    jTablename.getModel().setValueAt("", i, 0);
                   jTablename.getModel().setValueAt("", i, 3);
                   jTablename.getModel().setValueAt("", i, 4);
                   jTablename.getModel().setValueAt("", i, 5);

                    jTablename.getModel().setValueAt("", i, 6);
                   jTablename.getModel().setValueAt("", i, 7);

                    i=i-1;
                }
                i=0;
                String q="Select gl_no,ac_no from member where cust_no='"+accnoonly+"'";
                try{
                stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                 current = stmt.executeQuery(q);
           
           
                int j=0;
                 while(current.next()){
                     jTablename2.getModel().setValueAt(acctitle, j, 0);
                     jTablename2.getModel().setValueAt(current.getString("gl_no"), j, 1);
                     jTablename2.getModel().setValueAt(current.getString("ac_no"), j, 2);
                     j=j+1;
                 }
                 row_count=j;
                }
                 catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
               
                //current.close();
                //conn.close();
                             }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(rootPane, e.getMessage());
                  }
                
 this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                
                    }
                   
                    //format the Date 
                  
          
                  
        
    


    }//GEN-LAST:event_jTablenameMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
///clear previous search
       
        jTextFieldAcc.requestFocusInWindow(); 

    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldAccKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAccKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    jButtonsearch.doClick();
}
    }//GEN-LAST:event_jTextFieldAccKeyPressed

    private void jTablenameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablenameKeyPressed
 
  String sqlaccinfo="select m.cust_no cnum,name,ref_no,reg_date,phone,id_card,group_name,address,Bank_VNO,gl_no,ac_no,NUBAN_CODE,ac_status from member m inner join customer c on m.cust_no=c.cust_no" +
" where ac_no='"+jTablename.getModel().getValueAt(jTablename.getSelectedRow(),3)+"' and gl_no like'200%'";
          
            
  
                  try{
                      this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                ResultSet current = stmt.executeQuery(sqlaccinfo);
                 current.next();
                 acctitle=current.getString("name");
                 regdate=current.getString("reg_date");
                 groupname=current.getString("group_name");
                 idcard=current.getString("ID_card");
                 cusno=current.getString("cnum");
                 BVN=current.getString("Bank_VNO");
                 accnoonly=current.getString("ac_no");
                accno=current.getString("gl_no")+"-"+current.getString("ac_no");
                nuban=current.getString("nuban_code");
                ref=current.getString("ref_no");
                phone=current.getString("phone");
                addr=current.getString("address");
                status=current.getString("ac_status");
                if(status.equalsIgnoreCase("A")){status="Active";}
                else if(status.equalsIgnoreCase("C")){status="Closed";}
                else if(status.equalsIgnoreCase("D")){status="Dormant";}
                else if(status.equalsIgnoreCase("H")){status="On Hold";}
                this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                while(i>=0){
                     jTablename.getModel().setValueAt("", i, 0);
                    jTablename.getModel().setValueAt("", i, 3);
                    jTablename.getModel().setValueAt("", i, 4);
                    jTablename.getModel().setValueAt("", i, 5);

                    jTablename.getModel().setValueAt("", i, 6);
                    jTablename.getModel().setValueAt("", i, 7);

                     i=i-1;
                }
                i=0;
                this.dispose();
                current.close();
                conn.close();
                             }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(rootPane, e.getMessage());
                  }
                
 
                
                            // TODO add your handling code here:
    }//GEN-LAST:event_jTablenameKeyPressed

    private void jScrollPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane1ComponentShown
             // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1ComponentShown

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    // if(i>0){
   for(int n=0; n<=i; n++){
                     jTablename.getModel().setValueAt("", n, 0);
                    jTablename.getModel().setValueAt("", n, 3);
                    jTablename.getModel().setValueAt("", n, 4);
                    jTablename.getModel().setValueAt("", n, 5);

                    jTablename.getModel().setValueAt("", n, 6);
                    jTablename.getModel().setValueAt("", n, 7);

   }
   i=0;
   
   jTextFieldAcc.requestFocusInWindow();
//}        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jTablename2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablename2MouseClicked
if(evt.getClickCount()==2 && !jTablename2.getModel().getValueAt(jTablename2.getSelectedRow(),1).toString().isEmpty())  {
    
SelectedAcc=jTablename2.getModel().getValueAt(jTablename2.getSelectedRow(),1).toString()+"-"+jTablename2.getModel().getValueAt(jTablename2.getSelectedRow(),2).toString();
importAcc=true;
//JOptionPane.showMessageDialog(rootPane, row_count);
row_count=row_count-1;
while(row_count>=0){
                    jTablename2.getModel().setValueAt("", row_count, 0);
                   jTablename2.getModel().setValueAt("", row_count, 1);
                   jTablename2.getModel().setValueAt("", row_count, 2);
                   

                    

                    row_count=row_count-1;
                }
this.dispose();

}
    }//GEN-LAST:event_jTablename2MouseClicked

    private void jTablename2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablename2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTablename2KeyPressed

    private void jScrollPane2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jScrollPane2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2ComponentShown

    private void jTextFieldAcc2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAcc2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAcc2KeyPressed

    private void jButtonsearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearch1ActionPerformed
String qq;
if(jTextFieldAcc.getText().isEmpty()){
    JOptionPane.showMessageDialog(this, "You must type \n something to search");
}else{
/////Clear previous search (if any)

    i=0;

        
    qq=query="select  branch,cust_no,name,id_card,address,phone,ref_no,Bank_VNO from customer where name like'%"+jTextFieldAcc.getText()+"%'"; 

//JOptionPane.showMessageDialog(rootPane, query);
        try{
            
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
               
                ResultSet current = stmt.executeQuery(qq);
                 this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
                   jTablename.getColumnModel().getColumn(4).setPreferredWidth(100);
               jTablename.getColumnModel().getColumn(4).setPreferredWidth(400);
               jTablename.getColumnModel().getColumn(5).setPreferredWidth(500);
               
                 while(current.next()){
                     jTablename.getModel().setValueAt(current.getString("branch"), i, 0);
                    jTablename.getModel().setValueAt(current.getString("cust_no"), i, 3);
                    jTablename.getModel().setValueAt(current.getString("name").trim(), i, 4);
                    jTablename.getModel().setValueAt(current.getString("ref_no").trim()+"-"+current.getString("address").trim(), i, 5);

                    jTablename.getModel().setValueAt(current.getString("id_card"), i, 6);
                    jTablename.getModel().setValueAt(current.getString("Bank_VNO"), i, 7);

                     i=i+1;
                 }
                 
                 
                  this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));  
                 //JOptionPane.showMessageDialog(rootPane, i+" Records found ");
                   jTablename.requestFocusInWindow();
                  
                 current.close();                     

                 
}
catch(HeadlessException | SQLException e){JOptionPane.showMessageDialog(rootPane, e.getMessage());
}
  
 jTablename.requestFocusInWindow();

}          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonsearch1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientnameonly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientnameonly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientnameonly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientnameonly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientnameonly().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JButton jButtonsearch1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTablename;
    public javax.swing.JTable jTablename2;
    public javax.swing.JTextField jTextFieldAcc;
    public javax.swing.JTextField jTextFieldAcc2;
    // End of variables declaration//GEN-END:variables
Global glob = new Global();
Connection conn=glob.getConnect();

String BVN,acctitle,nuban,accno="n",status,cusno,addr,ref,phone,branch,regdate,idcard,groupname, accnoonly,SelectedAcc;
String query;
int i=0;
boolean importAcc=true;
int row_count=0;
}
