/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omfbreports;



//pdf to jpeg
import java.io.File;
import java.io.FileInputStream;
import javax.print.PrintServiceLookup;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.JOptionPane;
///

import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.sql.Connection;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.print.PrintService;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.printing.PDFPageable;

////////////////////

import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.HashMap;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
//////////////////////////////////

/**
 *
 * @author Emmanuel Ikpe
 */
public class ReportControl extends javax.swing.JFrame {

    /**
     * Creates new form ReportControl
     */
    public ReportControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUpdate = new javax.swing.JTable();
        jComboBoxAcctype = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabelosServer = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxuser = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jTextFieldDaily = new javax.swing.JTextField();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtontotal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldMB = new javax.swing.JTextField();
        jButtonDaily = new javax.swing.JButton();
        jButtonMB = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        OutstandingPI = new javax.swing.JMenuItem();
        OutstandingDate = new javax.swing.JMenuItem();
        OverdraftPrincipalBalance = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuSalary = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        RunDividend = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MFB CASH POSITION SYSTEM");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omfbreports/Resource/GLicon.PNG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omfbreports/Resource/ACCico.PNG"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omfbreports/Resource/uds-server-vdi-connection-broker.jpg__800x600_q85_subsampling-2.jpg"))); // NOI18N

        jButton3.setText("NUBAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/omfbreports/Resource/client icon.PNG"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTableUpdate.setBackground(new java.awt.Color(255, 153, 153));
        jTableUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTableUpdate.setForeground(new java.awt.Color(0, 0, 204));
        jTableUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"   PHONE NO"},
                {"      BVN "},
                {"SIGN & PHOTO"},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "       UPDATE ACCOUNT HOLDER DETAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUpdate.setOpaque(false);
        jTableUpdate.setRowHeight(22);
        jTableUpdate.setShowHorizontalLines(isEnabled());
        jTableUpdate.setShowVerticalLines(isEnabled());
        jTableUpdate.getTableHeader().setReorderingAllowed(false);
        jTableUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUpdateMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUpdate);
        if (jTableUpdate.getColumnModel().getColumnCount() > 0) {
            jTableUpdate.getColumnModel().getColumn(0).setResizable(false);
        }

        jComboBoxAcctype.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBoxAcctype.setForeground(new java.awt.Color(153, 153, 153));
        jComboBoxAcctype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Account Type>", "Savings Deposit Account", "Joint Account", "Corporate Account", "Current Account", "Daily Contribution", "Term Deposit", " " }));
        jComboBoxAcctype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAcctypeActionPerformed(evt);
            }
        });

        jButton5.setText("PRTG");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setText("Print AGM Letter");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton6.setText("Marketer Collection");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabelosServer.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabelosServer.setForeground(new java.awt.Color(0, 153, 102));

        jButton7.setText("Audit Trail");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setText("JAVA DB");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("dd-MM-yyyy");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DAILY SAVINGS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("MOBILE BANKING");

        jButton10.setText("getMarketers");
        jButton10.setBorder(null);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTextFieldDaily.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldDaily.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextFieldTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButtontotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtontotal.setText("getTotal");
        jButtontotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 204, 204), new java.awt.Color(255, 51, 0), new java.awt.Color(51, 51, 51)));
        jButtontotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TOTAL");

        jTextFieldMB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldMB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButtonDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDailyActionPerformed(evt);
            }
        });

        jButtonMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jTextFieldDaily))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxuser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDaily, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButtontotal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldTotal)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldDaily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonDaily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jButtontotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonMB, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButton9)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jLabelosServer, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxAcctype, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBoxAcctype, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(91, 91, 91)
                                .addComponent(jButton6)
                                .addGap(43, 43, 43)
                                .addComponent(jButton8)
                                .addGap(35, 35, 35)
                                .addComponent(jButton9))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(155, 155, 155)
                        .addComponent(jLabelosServer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 129, Short.MAX_VALUE))
        );

        jMenu1.setText("Report");

        jMenuItem1.setText("OutstandingPrincipalBalance");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        OutstandingPI.setText("OutstandingPrincipalAndInterestBalance");
        OutstandingPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutstandingPIActionPerformed(evt);
            }
        });
        jMenu1.add(OutstandingPI);

        OutstandingDate.setText("OutstandingLastTransactionDate");
        OutstandingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OutstandingDateActionPerformed(evt);
            }
        });
        jMenu1.add(OutstandingDate);

        OverdraftPrincipalBalance.setText("OverdraftPrincipalBalance");
        OverdraftPrincipalBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverdraftPrincipalBalanceActionPerformed(evt);
            }
        });
        jMenu1.add(OverdraftPrincipalBalance);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Run Process");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("BATCH(Salaries 300 and below)");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuSalary.setText("BATCH (Salaries)");
        jMenuSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalaryActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuSalary);

        jMenuItem4.setText("BATCH(Salary Advance)");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        RunDividend.setText("RUN DIVIDEND ON SHARES");
        RunDividend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunDividendActionPerformed(evt);
            }
        });
        jMenu2.add(RunDividend);

        jMenuItem2.setText("RUN AGM Letters");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Print AGM Letters");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Certificate");

        jMenuItem5.setText("Share Cert");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem8.setText("Batch Share Cert");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Transaction");

        jMenu5.setText("Withdrawal");

        jMenuItem7.setText("TELLER 3");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
GLACC gl= new GLACC();
gl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
CusAcc ac= new CusAcc();
ac.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Nuban nuban = new Nuban();
  nuban.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Clients client= new Clients(); 
client.conn=conn;
client.setVisible(true);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JRCViewReport.REPORT_NAME=jMenuItem1.getText()+".rpt";
        JRCViewReport.launchApplication();


        



    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void OutstandingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutstandingDateActionPerformed
 JRCViewReport.REPORT_NAME=OutstandingDate.getText()+".rpt";
       JRCViewReport.launchApplication();

		       
    }//GEN-LAST:event_OutstandingDateActionPerformed

    private void OutstandingPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OutstandingPIActionPerformed
 JRCViewReport.REPORT_NAME=OutstandingPI.getText()+".rpt";
        JRCViewReport.launchApplication();        // TODO add your handling code here:
    }//GEN-LAST:event_OutstandingPIActionPerformed

    private void jComboBoxAcctypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAcctypeActionPerformed
if(jComboBoxAcctype.getSelectedItem().toString().equalsIgnoreCase("Savings Deposit Account")){
    jTableUpdate.getModel().setValueAt("Sign Card", 3, 0);
    jTableUpdate.getModel().setValueAt("App Letter", 4, 0);
    jTableUpdate.getModel().setValueAt("Personal Data", 5, 0);
    jTableUpdate.getModel().setValueAt("Sign Form", 6, 0);
    jTableUpdate.getModel().setValueAt("ATM FORM", 7, 0);
    jTableUpdate.getModel().setValueAt("ID Card", 8, 0);
    jTableUpdate.getModel().setValueAt("NEPA BILL", 9, 0);
     jTableUpdate.getModel().setValueAt("", 10, 0);
      jTableUpdate.getModel().setValueAt("", 11, 0);
    
    } 
else if(jComboBoxAcctype.getSelectedItem().toString().equalsIgnoreCase("Corporate Account")){
    jTableUpdate.getModel().setValueAt("Resolution Form", 3, 0);
    jTableUpdate.getModel().setValueAt("Signature Card", 4, 0);
    jTableUpdate.getModel().setValueAt("Application Letter", 5, 0);
    jTableUpdate.getModel().setValueAt("Personal Data", 6, 0);
    jTableUpdate.getModel().setValueAt("Sign Form", 7, 0);
    jTableUpdate.getModel().setValueAt("ATM FORM", 8, 0);
    jTableUpdate.getModel().setValueAt("ID Card", 9, 0);
    jTableUpdate.getModel().setValueAt("NEPA BILL", 10, 0);
     jTableUpdate.getModel().setValueAt("", 11, 0);
}
else if(jComboBoxAcctype.getSelectedItem().toString().equalsIgnoreCase("Joint Account")){
    jTableUpdate.getModel().setValueAt("Mandate Form", 3, 0);
    jTableUpdate.getModel().setValueAt("Sign Card", 4, 0);
    jTableUpdate.getModel().setValueAt("App Letter", 5, 0);
    jTableUpdate.getModel().setValueAt("Personal Data", 6, 0);
    jTableUpdate.getModel().setValueAt("Sign Form", 7, 0);
    jTableUpdate.getModel().setValueAt("ATM FORM", 8, 0);
    jTableUpdate.getModel().setValueAt("ID Card", 9, 0);
    jTableUpdate.getModel().setValueAt("NEPA BILL", 10, 0);
     jTableUpdate.getModel().setValueAt("", 11, 0);
}
else if(jComboBoxAcctype.getSelectedItem().toString().equalsIgnoreCase("Current Account")){
    jTableUpdate.getModel().setValueAt("introduction Form", 3, 0);
    jTableUpdate.getModel().setValueAt("Corporate Affairs Form", 4, 0);
    jTableUpdate.getModel().setValueAt("Sign Card", 5, 0);
    jTableUpdate.getModel().setValueAt("App Letter", 6, 0);
    jTableUpdate.getModel().setValueAt("Personal Data", 7, 0);
    jTableUpdate.getModel().setValueAt("Sign Form", 8, 0);
    jTableUpdate.getModel().setValueAt("ATM FORM", 9, 0);
    jTableUpdate.getModel().setValueAt("ID Card", 10, 0);
    jTableUpdate.getModel().setValueAt("NEPA BILL", 11, 0);
}
else if(jComboBoxAcctype.getSelectedItem().toString().equalsIgnoreCase("Daily Contribution")){
jTableUpdate.getModel().setValueAt("Sign Card", 3, 0);
    jTableUpdate.getModel().setValueAt("App Letter", 4, 0);
    jTableUpdate.getModel().setValueAt("Personal Data", 5, 0);
    jTableUpdate.getModel().setValueAt("Sign Form", 6, 0);
    jTableUpdate.getModel().setValueAt("ATM FORM", 7, 0);
    jTableUpdate.getModel().setValueAt("ID Card", 8, 0);
    jTableUpdate.getModel().setValueAt("NEPA BILL", 9, 0);
     jTableUpdate.getModel().setValueAt("", 10, 0);
      jTableUpdate.getModel().setValueAt("", 11, 0);
}
else if(jComboBoxAcctype.getSelectedItem().toString().equalsIgnoreCase("Term Deposit")||jComboBoxAcctype.getSelectedItem().toString().equalsIgnoreCase("Fixed Deposit")){

jTableUpdate.getModel().setValueAt("Sign Card", 3, 0);
    jTableUpdate.getModel().setValueAt("App Letter", 4, 0);
    jTableUpdate.getModel().setValueAt("Personal Data", 5, 0);
    jTableUpdate.getModel().setValueAt("Sign Form", 6, 0);
    jTableUpdate.getModel().setValueAt("ATM FORM", 7, 0);
    jTableUpdate.getModel().setValueAt("ID Card", 8, 0);
    jTableUpdate.getModel().setValueAt("NEPA BILL", 9, 0);}
 jTableUpdate.getModel().setValueAt("", 10, 0);
  jTableUpdate.getModel().setValueAt("", 11, 0);






    }//GEN-LAST:event_jComboBoxAcctypeActionPerformed

    private void jTableUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUpdateMouseClicked
if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("introduction Form")){
    
 Updateform ufm= new Updateform();
 ufm.jLabelform.setText("intro Form");
 ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
 
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("Corporate Affairs Form")){

    
 Updateform ufm= new Updateform();
 ufm.jLabelform.setText("Corporate Affairs");
 ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true); 
    
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("Sign Card")){
  Updateform ufm= new Updateform();
   ufm.jLabelform.setText("Signature Card");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().startsWith("App")){
  Updateform ufm= new Updateform();
   ufm.jLabelform.setText("Application Letter");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("Personal Data")){
  Updateform ufm= new Updateform();
   ufm.jLabelform.setText("Personal Data");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("Sign Form")){
  Updateform ufm= new Updateform();
   ufm.jLabelform.setText("Sign Form");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
}

else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("ATM FORM")){
  Updateform ufm= new Updateform();
   ufm.jLabelform.setText("ATM FORM");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("ID Card")){
  Updateform ufm= new Updateform();
   ufm.jLabelform.setText("ID Card");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("NEPA BILL")){
  Updateform ufm= new Updateform();
   ufm.jLabelform.setText("NEPA BILL");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("Mandate Form")){
  Updateform ufm= new Updateform();
   ufm.jLabelform.setText("Mandate");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(true);ufm.jTextFieldform.setVisible(true);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(true);
 ufm.setVisible(true);   
}
//////////////////////////photo and sign
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().equalsIgnoreCase("Sign & Photo")){
  UpdateformBvn ufm= new UpdateformBvn();
   //ufm.jLabelform.setText("NEPA BILL");
  ufm.jLabelPhoto.setVisible(true);ufm.jTextFieldphoto.setVisible(true);
 ufm.jLabelSign.setVisible(true);ufm.jTextFieldSign.setVisible(true);
 ufm.jLabelPhone.setVisible(false);ufm.jTextFieldPhone.setVisible(false);
 ufm.jLabelform.setVisible(false);ufm.jTextFieldform.setVisible(false);
 ufm.jButtonsearch1.setVisible(true);
 ufm.jButtonsearch2.setVisible(true);
 ufm.jButtonsearch3.setVisible(false);
 ufm.setVisible(true);   
}   
  
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().contains("BVN")){
  UpdateformBvn ufm= new UpdateformBvn();
   //ufm.jLabelform.setText("NEPA BILL");
  ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);
 ufm.jLabelSign.setVisible(false);ufm.jTextFieldSign.setVisible(false);
 ufm.jLabelPhone.setVisible(true);ufm.jTextFieldPhone.setVisible(true);
 
 ufm.jLabelPhone.setText("BVN NO:");
 ufm.jLabelform.setVisible(false);ufm.jTextFieldform.setVisible(false);
 ufm.jButtonsearch1.setVisible(false);
 ufm.jButtonsearch2.setVisible(false);
 ufm.jButtonsearch3.setVisible(false);
 ufm.setVisible(true);   
}
else if(jTableUpdate.getModel().getValueAt(jTableUpdate.getSelectedRow(), 0).toString().contains("PHONE NO")){
  GSMform ufm= new GSMform();
   
 // ufm.jLabelPhoto.setVisible(false);ufm.jTextFieldphoto.setVisible(false);

 ufm.setVisible(true);   
}
    }//GEN-LAST:event_jTableUpdateMouseClicked

    private void OverdraftPrincipalBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverdraftPrincipalBalanceActionPerformed
JRCViewReport.REPORT_NAME=OverdraftPrincipalBalance.getText()+".rpt";
       JRCViewReport.launchApplication();        // TODO add your handling code here:
    }//GEN-LAST:event_OverdraftPrincipalBalanceActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
Connections check = new Connections();
check.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalaryActionPerformed
importSalary batch= new importSalary();
batch.setVisible(true); 
    }//GEN-LAST:event_jMenuSalaryActionPerformed

    private void RunDividendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunDividendActionPerformed
SharePosting batch= new SharePosting();
batch.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_RunDividendActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
AGMInvite AGM= new  AGMInvite();
AGM.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

         String printerName="\\\\CUSTOMERCARE-PC\\HP LaserJet Professional P1102";
  PrintRequestAttributeSet aset = new HashPrintRequestAttributeSet();  
 File folder = new File("AGMletters//");
        FileInputStream inputStream = null;
        File[] listOfFiles = folder.listFiles();
        for (int i = 0; i < listOfFiles.length; i++) {
  if (listOfFiles[i].isFile()) {

        try {
            inputStream = new FileInputStream("AGMletters\\"+listOfFiles[i].getName());
        
 PrintService printService=PrintServiceLookup.lookupDefaultPrintService();
       
        PDDocument pdf = PDDocument.load(inputStream);
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintService(printService);
        job.setPageable(new PDFPageable(pdf));
        job.print(aset);
        pdf.close();
 
    } catch (PrinterException | IOException | NullPointerException e) {
         try{ // beginning of try
             BufferedWriter writer = new BufferedWriter(new FileWriter("log.txt", true));
         
    
    writer.append("Not printed for "+listOfFiles[i].getName()+" and SN="+i+"");
     
    writer.close();
       JOptionPane.showMessageDialog(rootPane, e.getMessage());
     
  }//end of try
  catch(Exception ee){JOptionPane.showMessageDialog(rootPane, ee.getMessage());}
         
    }
  }//end of if
        }// end of for
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 PrintRequestAttributeSet aset = new HashPrintRequestAttributeSet();  
 File folder = new File("AGMletters//");
        FileInputStream inputStream = null;
        File[] listOfFiles = folder.listFiles();
        for (int i = 0; i < listOfFiles.length; i++) {
  if (listOfFiles[i].isFile()) {

        try {
            inputStream = new FileInputStream("AGMletters\\"+listOfFiles[i].getName());
        
 PrintService printService=PrintServiceLookup.lookupDefaultPrintService();
       
        PDDocument pdf = PDDocument.load(inputStream);
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintService(printService);
        job.setPageable(new PDFPageable(pdf));
        job.print(aset);
        pdf.close();
 
    } catch (PrinterException | IOException | NullPointerException e) {
         try{ // beginning of try
             BufferedWriter writer = new BufferedWriter(new FileWriter("log.txt", true));
         
    
    writer.append("Not printed for "+listOfFiles[i].getName()+" and SN="+i+"");
     
    writer.close();
       JOptionPane.showMessageDialog(rootPane, e.getMessage());
     
  }//end of try
  catch(Exception ee){JOptionPane.showMessageDialog(rootPane, ee.getMessage());}
         
    }
  }//end of if
        }// end of for
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
    
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
importDailySaving Mtpd= new  importDailySaving();
//MarketerPAD Mtpd= new MarketerPAD();  
Mtpd.setVisible(true);


    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
Calendar now=Calendar.getInstance();

SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
 // JOptionPane.showMessageDialog(rootPane, now.getTime().toString());
  
        Date dt =new Date(sdf.format(now.getTime()));
     jDateChooser1.setDate(dt);
        
        Date today= new Date();

        try {
        Date    expdate = new SimpleDateFormat("yyyy-MM-dd").parse("2020-09-14");
        long interval=expdate.getTime()-today.getTime();
        
        interval=interval/86400000;// days in nanoseconds
        //interval=30;//only use for testing
        //JOptionPane.showMessageDialog(this,"Java engine will expire in  "+interval+" days");
        if(interval>30){
     jLabelosServer.setText("Connected to "+glob.OsServer);  
      
                                        }
        else if (interval>0){
          jLabelosServer.setText("Connected to "+glob.OsServer);   
         JOptionPane.showMessageDialog(this,"Java engine will expire in  "+interval+" day(s) time"); 
        }
       else if(interval<0 ){
    JOptionPane.showMessageDialog(rootPane, "Your Java engine has expired. \n"+"Please visit https://www.java.com/en/ \n"
    +"http://www.oracle.com/us/corporate/pricing/price-lists/ or any of our local dealers");
    System.exit(0);
                                       }
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

 






    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
importparameter impara=  new importparameter();
impara.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
String pwd=JOptionPane.showInputDialog("Enter Your Password");
if(pwd.equals("rOcK")){
    GenShareCert certpara= new  GenShareCert();
              certpara.setVisible(true);
}else{
    JOptionPane.showMessageDialog(rootPane, "You are not authorized \n your face has been captiured \n the police will be notified");
}
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
AuditTrail AT= new AuditTrail(); 
AT.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
importSalarymini batch= new importSalarymini();
batch.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
  CashierWithdrawal cwdr= new  CashierWithdrawal() ;
cwdr.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
String pwd=JOptionPane.showInputDialog("Enter Your Password");
if(pwd.equals("rOcK")){
    GenShareCertBatch certpara= new  GenShareCertBatch();
              certpara.setVisible(true);
}else{
    JOptionPane.showMessageDialog(rootPane, "You are not authorized \n your face has been captiured \n the police will be notified");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        /*  Connection con = null;
        try {

            // con = DriverManager.getConnection(
                //  "jdbc:derby://localhost:1527/license","sa","Admin123Server"); //for network connection
            con = DriverManager.getConnection(
                "jdbc:derby:license;Create=true");  //embeded db
            Statement stmt = con.createStatement();

            //selecting rows
            ResultSet current=stmt.executeQuery("select * from certno");
            if(current.next()){

                JOptionPane.showMessageDialog(rootPane,"ok");

                // inserting rows

                //stmt.executeUpdate("update certno set certno='"+certno+"'");

            }
            stmt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Exception: "+e.getMessage());
        } */
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

Global glob= new Global();
Connection conn= glob.getConnect();
String dd=jDateChooser1.getDate().toString();
        String m="";
        if(dd.contains("Jan")){m="01";}
        else if(dd.contains("Feb")){m="02";}
         else if(dd.contains("Mar")){m="03";}
         else if(dd.contains("Apr")){m="04";}
         else if(dd.contains("May")){m="05";}
         else if(dd.contains("Jun")){m="06";}
        else if(dd.contains("Jul")){m="07";}
        else if(dd.contains("Aug")){m="08";}
        else if(dd.contains("Sep")){m="09";}
        else if(dd.contains("Oct")){m="10";}
        else if(dd.contains("Nov")){m="11";}
        else if(dd.contains("Dec")){m="12";}
String dtt= dd.substring(dd.length()-4)+"-"+m+"-"+dd.substring(8,10);

String usersql=" select distinct username from memtrans m inner join trx_text t on m.trx_no=t.trx_no " +
" where   gl_no='200301' and m.trx_no like '%DSDA' and m.ses_date='"+dtt+"' and username not in ('SYSTEM','COPYOF')" +
" order by username";
        jComboBoxuser.removeAllItems();
     
        try{
               Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                ResultSet current = stmt.executeQuery(usersql);

          
            while(current.next()){
              
               jComboBoxuser.addItem(current.getString("username")); 
            }
                current.close();
                conn.close();
            }
            catch(Exception e){ JOptionPane.showMessageDialog(this,e.getMessage());}
                  // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtontotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontotalActionPerformed
Global glob= new Global();
Connection conn= glob.getConnect();

       String dd=jDateChooser1.getDate().toString();
        String m="";
        if(dd.contains("Jan")){m="01";}
        else if(dd.contains("Feb")){m="02";}
         else if(dd.contains("Mar")){m="03";}
         else if(dd.contains("Apr")){m="04";}
         else if(dd.contains("May")){m="05";}
         else if(dd.contains("Jun")){m="06";}
        else if(dd.contains("Jul")){m="07";}
        else if(dd.contains("Aug")){m="08";}
        else if(dd.contains("Sep")){m="09";}
        else if(dd.contains("Oct")){m="10";}
        else if(dd.contains("Nov")){m="11";}
        else if(dd.contains("Dec")){m="12";}
String dtt= dd.substring(dd.length()-4)+"-"+m+"-"+dd.substring(8,10);

String totalDailysql=" select -SUM(amount) Total,count(amount) num   from memtrans m inner join trx_text t on m.trx_no=t.trx_no " +
" where m.ses_date='"+dtt+"' and username='"+jComboBoxuser.getSelectedItem().toString()+"' and gl_no='200301' and ac_no<>'3' and err_flag<>'E'";

String totalMbsql=" select SUM(amount) Total,count(amount) num from memtrans m inner join trx_text t on m.trx_no=t.trx_no " +
" where m.ses_date='"+dtt+"' and username='"+jComboBoxuser.getSelectedItem().toString()+"' and gl_no<>'200301' and ac_no='3' and err_flag<>'E' ";

if(dtt.length()<10){dtt=dtt.substring(0,5)+"0"+dtt.substring(5);};// to take care of 01/03/2018
double MB=0;
int c=0,cc=0,ccc=0;
     
        try{
               Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
               //fetching for daily savings
                ResultSet current = stmt.executeQuery(totalDailysql);
                if(current.next()){
                jTextFieldDaily.setText(current.getString("Total")); 
                c=current.getInt("num");
                }
                else{
                   jTextFieldDaily.setText("0.00"); 
                }
                //Fetching for Mobile Banking Savings
                current = stmt.executeQuery(totalMbsql);
                if(current.next()){
                jTextFieldTotal.setText(current.getString("Total")); 
                 cc=current.getInt("num");
                }
                else{
                    jTextFieldTotal.setText("0.00"); 
                    jTextFieldMB.setText("0.00"); 
                    jTextFieldDaily.setText("0.00"); 
                }
ccc=cc-c;                
MB= Double.parseDouble(jTextFieldTotal.getText())-Double.parseDouble(jTextFieldDaily.getText());
         if(!jTextFieldTotal.getText().equalsIgnoreCase("0.00")){
          jTextFieldMB.setText(MB+"("+ccc+")"); 
          jTextFieldDaily.setText(jTextFieldDaily.getText()+"("+c+")");
          jTextFieldTotal.setText(jTextFieldTotal.getText()+"("+cc+")");
         }
              
               
           
                current.close();
                conn.close();
            }
            catch(Exception e){ JOptionPane.showMessageDialog(this,e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtontotalActionPerformed

    private void jButtonDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDailyActionPerformed
String dd=jDateChooser1.getDate().toString();
        String m="";
        if(dd.contains("Jan")){m="01";}
        else if(dd.contains("Feb")){m="02";}
         else if(dd.contains("Mar")){m="03";}
         else if(dd.contains("Apr")){m="04";}
         else if(dd.contains("May")){m="05";}
         else if(dd.contains("Jun")){m="06";}
        else if(dd.contains("Jul")){m="07";}
        else if(dd.contains("Aug")){m="08";}
        else if(dd.contains("Sep")){m="09";}
        else if(dd.contains("Oct")){m="10";}
        else if(dd.contains("Nov")){m="11";}
        else if(dd.contains("Dec")){m="12";}
String dtt= dd.substring(dd.length()-4)+"-"+m+"-"+dd.substring(8,10);
        try
 {InputStream in = new FileInputStream(new File("C:\\ReportO\\DailySavings.jrxml"));
            

            
String sql=" select reg_date,gl_no,ac_no,name,Replace(text,'CASH DEP BY','') Depositor,username,-amount amount from memtrans m inner join trx_text t on m.trx_no=t.trx_no " +
" inner join customer c on m.ac_no=c.cust_no  " +
" where m.ses_date='"+dtt+"' and err_flag<>'E' and gl_no='200301' and amount<0 and ac_no<>'3' and m.trx_no like '%DSDA' " +
" order by username";
  // JOptionPane.showMessageDialog(this,sql);
        this.displayReport(in,sql,"fromdate",dtt);
 }
 catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
        
    
    }//GEN-LAST:event_jButtonDailyActionPerformed

    private void jButtonMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMBActionPerformed
String dd=jDateChooser1.getDate().toString();
        String m="";
        if(dd.contains("Jan")){m="01";}
        else if(dd.contains("Feb")){m="02";}
         else if(dd.contains("Mar")){m="03";}
         else if(dd.contains("Apr")){m="04";}
         else if(dd.contains("May")){m="05";}
         else if(dd.contains("Jun")){m="06";}
        else if(dd.contains("Jul")){m="07";}
        else if(dd.contains("Aug")){m="08";}
        else if(dd.contains("Sep")){m="09";}
        else if(dd.contains("Oct")){m="10";}
        else if(dd.contains("Nov")){m="11";}
        else if(dd.contains("Dec")){m="12";}
String dtt= dd.substring(dd.length()-4)+"-"+m+"-"+dd.substring(8,10);
        try
 {InputStream in = new FileInputStream(new File("C:\\ReportO\\MobileSavings.jrxml"));
            
String sql="select reg_date,gl_no,ac_no,name,Replace(text,'CASH DEP BY','') Depositor,username,-amount amount from memtrans m inner join trx_text t on m.trx_no=t.trx_no " +
" inner join customer c on m.ac_no=c.cust_no  " +
" where m.ses_date='"+dtt+"' and err_flag<>'E' and gl_no<>'200301' and amount<0 and ac_no<>'3' and m.trx_no like '%DSDA' " +
" order by username";
            

  // JOptionPane.showMessageDialog(this,sql);
        this.displayReport(in,sql,"fromdate",dtt);
 }
 catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OutstandingDate;
    private javax.swing.JMenuItem OutstandingPI;
    private javax.swing.JMenuItem OverdraftPrincipalBalance;
    private javax.swing.JMenuItem RunDividend;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDaily;
    private javax.swing.JButton jButtonMB;
    private javax.swing.JButton jButtontotal;
    private javax.swing.JComboBox<String> jComboBoxAcctype;
    private javax.swing.JComboBox<String> jComboBoxuser;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelosServer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuSalary;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableUpdate;
    private javax.swing.JTextField jTextFieldDaily;
    private javax.swing.JTextField jTextFieldMB;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
int i,maxsheet;
int salcount;
Global glob=new Global();
 Connection conn=glob.getConnect();
 String FILE_PATH="";
 
 
 public void displayReport(InputStream report,String sql,String paraname1,String paravalue1){
     try{
    JasperDesign jd= JRXmlLoader.load(report);
 
            JRDesignQuery newQuery= new JRDesignQuery();
           newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr= JasperCompileManager.compileReport(jd);
            HashMap para= new HashMap();
             para.put("Compname","OHAFIA MICROFINANCE BANK PLC"); 
             //JOptionPane.showMessageDialog(rootPane, companyname);
            if(!paravalue1.isEmpty()){
             para.put(paraname1,paravalue1);    
            }
           // if(!paravalue2.isEmpty()){
           //para.put(paraname2,paravalue2);   
           // }
                 
            JasperPrint j=JasperFillManager.fillReport(jr, para, glob.getConnect());
            
          
            JasperViewer.viewReport(j,false);
     }
     catch(Exception e){JOptionPane.showMessageDialog(rootPane, e.getMessage());}
            
 
}
 
}
