package omfbreports;

import java.awt.Color;
import javax.swing.*;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author Karyuu Ouji
 */
public class test extends javax.swing.JPanel {

    /**
     * Creates new form TestPanel
     */
    public test() {

        initComponents();
        this.setPreferredSize(new Dimension(800,1500));
        //this.setOpaque(true);
        //this.setDoubleBuffered(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(10, 0, 110, 23);
        //writing to image
        try{
         //acc_no = "113845";
        //cert_no = "113845";
        //name = "James Kalu Chidiebere";
        //share_no = "8785324";
        String[] shareno_text= {"","","","","","",""};
        int begin,end;
        for(int i=0;i<share_no.length();i++){
            begin=share_no.length()-i-1;
            end=share_no.length()-i;
        shareno_text[i]  =to_text(share_no.substring(begin,end));  
          // JOptionPane.showMessageDialog(this, shareno_text[i]);
        }
        BufferedImage bufferedImage =ImageIO.read(new File("SHARE CERTIFICATES.jpg"));
        Graphics graphics = bufferedImage.getGraphics();
       // graphics.setColor(Color.LIGHT_GRAY);
       // graphics.fillRect(0, 0, 200, 50);
        graphics.setColor(Color.BLACK);
        graphics.setFont(new Font("Arial Black", Font.BOLD, 20));
        graphics.drawString(cert_no, 60, 132);
        graphics.drawString(acc_no, 60, 250);
        graphics.drawString(share_no, 860, 132);
        graphics.drawString(name , 380, 300);
        graphics.setFont(new Font("Arial Black", Font.BOLD, 14));
        graphics.drawString(shareno_text[0] , 780, 450);
        graphics.drawString(shareno_text[1] , 700, 450);
        graphics.drawString(shareno_text[2] , 630, 450);
        graphics.drawString(shareno_text[3] , 550, 450);
        graphics.drawString(shareno_text[4] , 480, 450);
        graphics.drawString(shareno_text[5] , 400, 450);
        graphics.drawString(shareno_text[6] , 320, 450);
        
        ImageIO.write(bufferedImage, "jpg", new File(
                "Copy SHARE CERTIFICATES.jpg"));
        }
        catch(Exception e){JOptionPane.showMessageDialog(this, e.getMessage());}
        //////////////////////////

        jLabel1.setIcon(new ImageIcon(new javax.swing.ImageIcon("Copy SHARE CERTIFICATES.jpg").getImage().getScaledInstance(800,500,Image.SCALE_DEFAULT))); 
        jLabel2.setIcon(new ImageIcon(new javax.swing.ImageIcon(getClass().getResource("/omfbreports/SHARE CERTIFICATES.jpg")).getImage().getScaledInstance(100,200,Image.SCALE_DEFAULT))); 
        jLabel1.setText("");
        jLabel1.setText("");
        add(jLabel1);
        add(jLabel2);
          //jLabel1.setSize( 400, 800);
        jLabel1.setBounds(0, 0, 800, 500);
        jLabel2.setBounds(0, 510, 800, 800);
    }// </editor-fold>                        

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {                                       
        System.exit(0);
    }                                      

    public static void main(String[] args) {

        JFrame frmMain = new JFrame();
        frmMain.setUndecorated(true);
        frmMain.setBackground(new Color(0,0,0,0));
        frmMain.add(new test());
        frmMain.pack();
        frmMain.setLocationRelativeTo(null);
        frmMain.setVisible(true);

    }
    private String to_text(String input) {
        String output;
        if(input.equalsIgnoreCase("0")){output="ZERO";}
        else if(input.equalsIgnoreCase("1")){output="ONE";}
        else if(input.equalsIgnoreCase("2")){output="TWO";}
        else if(input.equalsIgnoreCase("3")){output="THREE";}
        else if(input.equalsIgnoreCase("4")){output="FOUR";}
        else if(input.equalsIgnoreCase("5")){output="FIVE";}
        else if(input.equalsIgnoreCase("6")){output="SIX";}
        else if(input.equalsIgnoreCase("7")){output="SEVEN";}
        else if(input.equalsIgnoreCase("8")){output="EIGHT";}
        else if(input.equalsIgnoreCase("9")){output="NINE";}
        else{output="";}
        return output;
        
    }


    // Variables declaration - do not modify   
    public String acc_no;
    public String cert_no ;
    public String name  ;
    public String share_no ;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}